name: Deploy JupyterLite site

on:
  push:
    branches: [ main ]   # change if your default branch is "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install JupyterLite
        run: |
          pip install jupyterlite[all]

      - name: Build JupyterLite site
        run: |
          jupyter lite build --output-dir dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
